import { defineField, defineType } from "sanity";

export const projectType = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "summary", title: "Summary", default: true },
    { name: "story", title: "Case Study" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "summary",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "summary",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      description: "e.g. Home Builder, Healthcare, Creative Studio",
      type: "string",
      group: "summary",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 3,
      group: "summary",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "image",
      title: "Cover image",
      type: "image",
      group: "summary",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "link",
      title: "Live site URL",
      type: "url",
      group: "summary",
    }),
    defineField({
      name: "order",
      title: "Display order",
      description: "Lower numbers show first.",
      type: "number",
      group: "summary",
      initialValue: 0,
    }),
    defineField({
      name: "client",
      title: "Client name",
      type: "string",
      group: "story",
    }),
    defineField({
      name: "projectDate",
      title: "Project date",
      type: "date",
      group: "story",
    }),
    defineField({
      name: "backgroundHeadline",
      title: "Background headline",
      description: "The story behind the project — why it was needed.",
      type: "string",
      group: "story",
    }),
    defineField({
      name: "backgroundBody",
      title: "Background body",
      type: "text",
      rows: 4,
      group: "story",
    }),
    defineField({
      name: "backgroundImages",
      title: "Background images",
      type: "array",
      group: "story",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (rule) => rule.max(2),
    }),
    defineField({
      name: "resultHeadline",
      title: "Result headline",
      description: "What the finished site achieved.",
      type: "string",
      group: "story",
    }),
    defineField({
      name: "resultBody",
      title: "Result body",
      type: "text",
      rows: 4,
      group: "story",
    }),
    defineField({
      name: "resultImages",
      title: "Result images",
      type: "array",
      group: "story",
      of: [{ type: "image", options: { hotspot: true } }],
      validation: (rule) => rule.max(2),
    }),
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "image" },
  },
});
